name: CI

on:
  push: ~
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup DMD
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: dmd-latest

      - name: Run tests
        run: |
          dub test

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup DMD
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: dmd-latest

      - name: Build library
        run: |
          dub build

  audit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup DMD
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: dmd-latest

      - name: Check style
        run: |
          dub fetch dscanner@0.12.2
          dub run dscanner -- --styleCheck src
